---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - env:
        - name: PORT
          value: "5000"
        image: gcr.io/devops-project-387804/gcpdevops-dev:latest
        name: gcp-devops-gke
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: gcp-devops-gke-service
    namespace: gcp-devops-dev
    labels:
     app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000    
  selector:
    app: gcp

  
