---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - env:
        - name: PORT
          value: "5000"
        image: gcr.io/devops-project-387804/gcpdevops:latest
        name: gcp-devops-gke
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: gcp-devops-gke-service
  namespace: gcp-devops-prod
spec:
  ports:
  - port: 80
    targetport: 5000
  selector:
    app: gcp
  type: LoadBalancer
